apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook
  namespace: guestbook
spec:
  rules:
  - host: smd-app.example.local
    http:
      paths:
      - backend:
          serviceName: kustomize-guestbook-ui
          servicePort: 80
